[package]
name = "attributes_attestation"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"]}
rand = "0.8"
sha2 = "0.10.9"
uuid = { version = "1.17.0", features = ["v4"] }
