# array_width = 100
# attr_fn_like_width = 100
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
# chain_width = 100
color = "Auto"
combine_control_expr = true
comment_width = 100 #80
condense_wildcard_suffixes = true #false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2021" #"2015"
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = false
error_on_unformatted = false
# fn_call_width = 100
fn_params_layout = "Compressed" #"Tall"
fn_single_line = true #false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true #false
doc_comment_code_block_width = 100
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
skip_macro_invocations = []
format_strings = true #false
hard_tabs = false
hex_literal_case = "Lower" #"Preserve"
hide_parse_errors = false
ignore = []
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 100 #0
match_arm_blocks = false #true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true #false
max_width = 100
merge_derives = true
imports_granularity = "Module" #"Preserve"
newline_style = "Auto"
normalize_comments = true #false
normalize_doc_attributes = true #false
overflow_delimited_expr = true #false
remove_nested_parens = true
reorder_impl_items = true #false
reorder_imports = true
group_imports = "StdExternalCrate" #"Preserve"
reorder_modules = true
#required_version = "CARGO_PKG_VERSION"
short_array_element_width_threshold = 100 #10
skip_children = false
# single_line_if_else_max_width = 100
# single_line_let_else_max_width = 100
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
# struct_lit_width = 100
# struct_variant_width = 100
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true #false
use_field_init_shorthand = true #false
use_small_heuristics = "Max" #"Default"
use_try_shorthand = true #false
#version = "One"
where_single_line = true #false
wrap_comments = true #false
